//Request
export const LIST_MOVIETHEATERFOLLOWTHEATER_REQUEST =
  "MovieFollowTheaterReducer/LIST_MOVIETHEATERFOLLOWTHEATER_REQUEST";
//Success
export const LIST_MOVIETHEATERFOLLOWTHEATER_SUCCESS =
  "MovieFollowTheaterReducer/LIST_MOVIETHEATERFOLLOWTHEATER_SUCCESS";

//Failed
export const LIST_MOVIETHEATERFOLLOWTHEATER_FAILED =
  "MovieFollowTheaterReducer/LIST_MOVIETHEATERFOLLOWTHEATER_FAILED";
